language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

#php:
#  - 5.5
#  - 5.6
#  - 7.0
#  - hhvm

matrix:
  include:
    - php: 7.0
      env: DEPS=dev

env:
  - COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi
  - if [ "$DEPS" == "dev" ]; then echo "dev!"; fi
  - perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json;

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
